export enum InventoryCategory {
  CLINICAL_SUPPLIES = 'CLINICAL_SUPPLIES',
  THERAPY_CONSUMABLES = 'THERAPY_CONSUMABLES',
  RETAIL_PRODUCTS = 'RETAIL_PRODUCTS',
  FACILITY_SUPPLIES = 'FACILITY_SUPPLIES',
  OFFICE_ADMIN = 'OFFICE_ADMIN',
}
