export enum StockMovementType {
  PURCHASE = 'PURCHASE',
  SALE = 'SALE',
  CONSUMPTION = 'CONSUMPTION',
  ADJUSTMENT_IN = 'ADJUSTMENT_IN',
  ADJUSTMENT_OUT = 'ADJUSTMENT_OUT',
  CORRECTION = 'CORRECTION',
  SCRAP = 'SCRAP',
}
