import { Module } from '@nestjs/common';
import { UNIT_OF_WORK } from '../persistence/unit-of-work.interface';
import { IDENTITY_CONTEXT } from './identity-context.interface';
import { PlaceholderIdentityContextService } from './placeholder-identity-context.service';
import {
  Argon2PasswordHasher,
  ConfigPasswordPolicyConfiguration,
  PASSWORD_HASHER,
  PASSWORD_POLICY_CONFIGURATION,
  PasswordPolicyService,
  TemporaryPasswordGeneratorService,
} from './password';
import {
  ACCESS_TOKEN_SERVICE,
  AccessTokenService,
  ConfigSecretProvider,
  ConfigTokenConfiguration,
  JwtTokenFactory,
  REFRESH_TOKEN_SERVICE,
  RefreshTokenService,
  SECRET_PROVIDER,
  TOKEN_CONFIGURATION,
  TOKEN_FACTORY,
  TOKEN_HASHER,
  Sha256TokenHasher,
} from './tokens';
import { LoggerSecurityEventPublisher, SECURITY_EVENT_PUBLISHER } from './events';
import { REFRESH_TOKEN_REPOSITORY, USER_REPOSITORY } from './domain';
import { AuthenticationGuard } from './guards';
import {
  AUTHORIZATION_EVALUATOR,
  AUTHORIZATION_SERVICE,
  AuthorizationGuard,
  DefaultAuthorizationEvaluator,
  DefaultAuthorizationService,
  DefaultPermissionResolver,
  PERMISSION_RESOLVER,
} from './authorization';
import { AsyncLocalStorageRequestContextAccessor, REQUEST_CONTEXT_ACCESSOR } from './context';
import { PrismaRefreshTokenRepository, PrismaUserRepository } from '../persistence/prisma';
import { CLOCK, SystemClock } from '../../shared/common/clock.interface';
import {
  ActivateUserUseCase,
  ChangePasswordUseCase,
  CreateUserUseCase,
  DeactivateUserUseCase,
  DeleteUserUseCase,
  ResetPasswordUseCase,
  SearchUsersUseCase,
  UpdateUserUseCase,
} from './use-cases';

import { AuthController } from './controllers/auth.controller';
import {
  LoginUseCase,
  RefreshTokenUseCase,
  LogoutUseCase,
  GetCurrentUserUseCase,
} from './use-cases';

@Module({
  controllers: [AuthController],
  providers: [
    PlaceholderIdentityContextService,
    {
      provide: IDENTITY_CONTEXT,
      useExisting: PlaceholderIdentityContextService,
    },
    ConfigPasswordPolicyConfiguration,
    {
      provide: PASSWORD_POLICY_CONFIGURATION,
      useClass: ConfigPasswordPolicyConfiguration,
    },
    Argon2PasswordHasher,
    {
      provide: PASSWORD_HASHER,
      useClass: Argon2PasswordHasher,
    },
    PasswordPolicyService,
    TemporaryPasswordGeneratorService,
    ConfigSecretProvider,
    {
      provide: SECRET_PROVIDER,
      useClass: ConfigSecretProvider,
    },
    ConfigTokenConfiguration,
    {
      provide: TOKEN_CONFIGURATION,
      useClass: ConfigTokenConfiguration,
    },
    JwtTokenFactory,
    {
      provide: TOKEN_FACTORY,
      useClass: JwtTokenFactory,
    },
    AccessTokenService,
    {
      provide: ACCESS_TOKEN_SERVICE,
      useClass: AccessTokenService,
    },
    RefreshTokenService,
    {
      provide: REFRESH_TOKEN_SERVICE,
      useClass: RefreshTokenService,
    },
    Sha256TokenHasher,
    {
      provide: TOKEN_HASHER,
      useClass: Sha256TokenHasher,
    },
    LoggerSecurityEventPublisher,
    {
      provide: SECURITY_EVENT_PUBLISHER,
      useClass: LoggerSecurityEventPublisher,
    },
    PrismaUserRepository,
    {
      provide: USER_REPOSITORY,
      useClass: PrismaUserRepository,
    },
    PrismaRefreshTokenRepository,
    {
      provide: REFRESH_TOKEN_REPOSITORY,
      useClass: PrismaRefreshTokenRepository,
    },
    SystemClock,
    {
      provide: CLOCK,
      useClass: SystemClock,
    },
    AuthenticationGuard,
    DefaultPermissionResolver,
    {
      provide: PERMISSION_RESOLVER,
      useClass: DefaultPermissionResolver,
    },
    DefaultAuthorizationEvaluator,
    {
      provide: AUTHORIZATION_EVALUATOR,
      useClass: DefaultAuthorizationEvaluator,
    },
    DefaultAuthorizationService,
    {
      provide: AUTHORIZATION_SERVICE,
      useClass: DefaultAuthorizationService,
    },
    AuthorizationGuard,
    AsyncLocalStorageRequestContextAccessor,
    {
      provide: REQUEST_CONTEXT_ACCESSOR,
      useClass: AsyncLocalStorageRequestContextAccessor,
    },
    {
      provide: LoginUseCase,
      useFactory: (
        userRepo,
        refreshRepo,
        hasher,
        tokenHasher,
        accessSvc,
        refreshSvc,
        clock,
        tokenConfig,
        eventPub,
      ) =>
        new LoginUseCase(
          userRepo,
          refreshRepo,
          hasher,
          tokenHasher,
          accessSvc,
          refreshSvc,
          clock,
          tokenConfig,
          eventPub,
        ),
      inject: [
        USER_REPOSITORY,
        REFRESH_TOKEN_REPOSITORY,
        PASSWORD_HASHER,
        TOKEN_HASHER,
        ACCESS_TOKEN_SERVICE,
        REFRESH_TOKEN_SERVICE,
        CLOCK,
        TOKEN_CONFIGURATION,
        SECURITY_EVENT_PUBLISHER,
      ],
    },
    {
      provide: RefreshTokenUseCase,
      useFactory: (
        userRepo,
        refreshRepo,
        tokenHasher,
        accessSvc,
        refreshSvc,
        clock,
        uow,
        tokenConfig,
        eventPub,
      ) =>
        new RefreshTokenUseCase(
          userRepo,
          refreshRepo,
          tokenHasher,
          accessSvc,
          refreshSvc,
          clock,
          uow,
          tokenConfig,
          eventPub,
        ),
      inject: [
        USER_REPOSITORY,
        REFRESH_TOKEN_REPOSITORY,
        TOKEN_HASHER,
        ACCESS_TOKEN_SERVICE,
        REFRESH_TOKEN_SERVICE,
        CLOCK,
        UNIT_OF_WORK,
        TOKEN_CONFIGURATION,
        SECURITY_EVENT_PUBLISHER,
      ],
    },
    {
      provide: LogoutUseCase,
      useFactory: (userRepo, refreshRepo, refreshSvc, tokenHasher, eventPub) =>
        new LogoutUseCase(userRepo, refreshRepo, refreshSvc, tokenHasher, eventPub),
      inject: [
        USER_REPOSITORY,
        REFRESH_TOKEN_REPOSITORY,
        REFRESH_TOKEN_SERVICE,
        TOKEN_HASHER,
        SECURITY_EVENT_PUBLISHER,
      ],
    },
    {
      provide: GetCurrentUserUseCase,
      useFactory: (userRepo) => new GetCurrentUserUseCase(userRepo),
      inject: [USER_REPOSITORY],
    },
    CreateUserUseCase,
    UpdateUserUseCase,
    ActivateUserUseCase,
    DeactivateUserUseCase,
    DeleteUserUseCase,
    SearchUsersUseCase,
    ChangePasswordUseCase,
    ResetPasswordUseCase,
  ],
  exports: [
    PlaceholderIdentityContextService,
    IDENTITY_CONTEXT,
    ConfigPasswordPolicyConfiguration,
    PASSWORD_POLICY_CONFIGURATION,
    Argon2PasswordHasher,
    PASSWORD_HASHER,
    PasswordPolicyService,
    TemporaryPasswordGeneratorService,
    ConfigSecretProvider,
    SECRET_PROVIDER,
    ConfigTokenConfiguration,
    TOKEN_CONFIGURATION,
    JwtTokenFactory,
    TOKEN_FACTORY,
    AccessTokenService,
    ACCESS_TOKEN_SERVICE,
    RefreshTokenService,
    REFRESH_TOKEN_SERVICE,
    Sha256TokenHasher,
    TOKEN_HASHER,
    LoggerSecurityEventPublisher,
    SECURITY_EVENT_PUBLISHER,
    PrismaUserRepository,
    USER_REPOSITORY,
    PrismaRefreshTokenRepository,
    REFRESH_TOKEN_REPOSITORY,
    SystemClock,
    CLOCK,
    AuthenticationGuard,
    DefaultPermissionResolver,
    PERMISSION_RESOLVER,
    DefaultAuthorizationEvaluator,
    AUTHORIZATION_EVALUATOR,
    DefaultAuthorizationService,
    AUTHORIZATION_SERVICE,
    AuthorizationGuard,
    AsyncLocalStorageRequestContextAccessor,
    REQUEST_CONTEXT_ACCESSOR,
    LoginUseCase,
    RefreshTokenUseCase,
    LogoutUseCase,
    GetCurrentUserUseCase,
    CreateUserUseCase,
    UpdateUserUseCase,
    ActivateUserUseCase,
    DeactivateUserUseCase,
    DeleteUserUseCase,
    SearchUsersUseCase,
    ChangePasswordUseCase,
    ResetPasswordUseCase,
  ],
})
export class IdentityModule {}
